"""durable delivery foundation

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("aggregate_type", sa.Text(), nullable=False),
        sa.Column("aggregate_id", sa.UUID(), nullable=False),
        sa.Column("aggregate_version", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(payload) = 'object'", name=op.f("ck_outbox_events_object_payload")
        ),
        sa.CheckConstraint(
            "(lease_until IS NULL) = (lease_token IS NULL)",
            name=op.f("ck_outbox_events_lease_pair"),
        ),
        sa.CheckConstraint("aggregate_version > 0", name=op.f("ck_outbox_events_positive_version")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
        sa.UniqueConstraint(
            "aggregate_type",
            "aggregate_id",
            "aggregate_version",
            "event_type",
            name="uq_outbox_aggregate_event",
        ),
    )
    op.create_index("ix_outbox_lease", "outbox_events", ["lease_until"], unique=False)
    op.create_index(
        "ix_outbox_pending", "outbox_events", ["published_at", "occurred_at"], unique=False
    )
    op.create_table(
        "webhook_inbox",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_event_id", sa.Text(), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("payload_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status = 'pending' OR verified", name=op.f("ck_webhook_inbox_verified_processing")
        ),
        sa.CheckConstraint(
            "status IN ('pending','processing','processed','ignored')",
            name=op.f("ck_webhook_inbox_status"),
        ),
        sa.CheckConstraint(
            "(lease_until IS NULL) = (lease_token IS NULL)",
            name=op.f("ck_webhook_inbox_lease_pair"),
        ),
        sa.CheckConstraint(
            "octet_length(payload_ciphertext) BETWEEN 1 AND 262144",
            name=op.f("ck_webhook_inbox_bounded_payload"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_inbox")),
        sa.UniqueConstraint("provider", "provider_event_id", name="uq_inbox_provider_event"),
    )
    op.create_index("ix_inbox_lease", "webhook_inbox", ["lease_until"], unique=False)
    op.create_index("ix_inbox_pending", "webhook_inbox", ["status", "received_at"], unique=False)
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("source_event_id", sa.UUID(), nullable=True),
        sa.Column("dedupe_key", sa.Text(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lease_token", sa.UUID(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_code", sa.Text(), nullable=True),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'running') = (lease_until IS NOT NULL AND lease_token IS NOT NULL)",
            name=op.f("ck_background_jobs_running_lease"),
        ),
        sa.CheckConstraint(
            "last_error_code IS NULL OR last_error_code IN "
            "('PROVIDER_UNAVAILABLE','CONFIGURATION_ERROR','UNKNOWN_OUTCOME','RETRY_EXHAUSTED')",
            name=op.f("ck_background_jobs_safe_error"),
        ),
        sa.CheckConstraint(
            "status IN ('queued','running','succeeded','failed','dead_letter')",
            name=op.f("ck_background_jobs_status"),
        ),
        sa.CheckConstraint(
            "(lease_until IS NULL) = (lease_token IS NULL)",
            name=op.f("ck_background_jobs_lease_pair"),
        ),
        sa.CheckConstraint(
            "attempt_count BETWEEN 0 AND 8", name=op.f("ck_background_jobs_bounded_attempts")
        ),
        sa.CheckConstraint("version > 0", name=op.f("ck_background_jobs_positive_version")),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["outbox_events.id"],
            name=op.f("fk_background_jobs_source_event_id_outbox_events"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_background_jobs")),
        sa.UniqueConstraint("kind", "dedupe_key", name="uq_job_kind_dedupe"),
    )
    op.create_index("ix_jobs_lease", "background_jobs", ["lease_until"], unique=False)
    op.create_index("ix_jobs_ready", "background_jobs", ["status", "next_attempt_at"], unique=False)
    op.create_index("ix_jobs_source", "background_jobs", ["source_event_id"], unique=False)
    # Delivery identities/payloads cannot be rewritten during retries/replay.
    op.execute("""
        CREATE FUNCTION zuno_guard_delivery_identity() RETURNS trigger
        LANGUAGE plpgsql AS $$
        BEGIN
          IF TG_TABLE_NAME = 'outbox_events' THEN
            IF ROW(NEW.id, NEW.aggregate_type, NEW.aggregate_id, NEW.aggregate_version,
                   NEW.event_type, NEW.payload, NEW.occurred_at, NEW.created_at)
               IS DISTINCT FROM
               ROW(OLD.id, OLD.aggregate_type, OLD.aggregate_id, OLD.aggregate_version,
                   OLD.event_type, OLD.payload, OLD.occurred_at, OLD.created_at) THEN
              RAISE EXCEPTION 'Immutable outbox identity';
            END IF;
          ELSIF TG_TABLE_NAME = 'background_jobs' THEN
            IF ROW(NEW.id, NEW.kind, NEW.source_event_id, NEW.dedupe_key,
                   NEW.payload, NEW.created_at)
               IS DISTINCT FROM
               ROW(OLD.id, OLD.kind, OLD.source_event_id, OLD.dedupe_key,
                   OLD.payload, OLD.created_at) THEN
              RAISE EXCEPTION 'Immutable job identity';
            END IF;
          ELSE
            IF ROW(NEW.id, NEW.provider, NEW.provider_event_id, NEW.verified,
                   NEW.payload_ciphertext, NEW.received_at, NEW.created_at)
               IS DISTINCT FROM
               ROW(OLD.id, OLD.provider, OLD.provider_event_id, OLD.verified,
                   OLD.payload_ciphertext, OLD.received_at, OLD.created_at) THEN
              RAISE EXCEPTION 'Immutable inbox identity';
            END IF;
          END IF;
          RETURN NEW;
        END $$;
    """)
    for table in ("outbox_events", "background_jobs", "webhook_inbox"):
        op.execute(
            f"CREATE TRIGGER guard_delivery_identity BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION zuno_guard_delivery_identity()"
        )


def downgrade() -> None:
    raise RuntimeError("Data-preserving application rollback only; use a reviewed forward fix")
