"""Narrow C01 portions of the approved ports and transaction-local plumbing."""

from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Protocol
from uuid import UUID

from zuno_edu.modules.identity.domain import (
    Account,
    Credential,
    MfaChallenge,
    MfaFactor,
    RecoveryCode,
    Session,
)


@dataclass(frozen=True)
class SelfAuthScope:
    account_id: UUID


@dataclass(frozen=True)
class AccountCredentials:
    account: Account
    credential: Credential


@dataclass(frozen=True, repr=False)
class IssuedToken:
    value: str
    token_hash: bytes
    subject: UUID
    purpose: str
    expires_at: datetime


@dataclass(frozen=True)
class EncryptedMfaSetup:
    secret_reference: bytes = field(repr=False)
    key_version: str
    otpauth_uri: str = field(repr=False)


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, password_hash: str) -> bool: ...
    def needs_rehash(self, password_hash: str) -> bool: ...


class TokenIssuer(Protocol):
    def issue(self, purpose: str, subject: UUID, ttl: timedelta) -> IssuedToken: ...
    def digest(self, token: str) -> bytes: ...
    def verify_digest(self, token: str, token_hash: bytes) -> bool: ...


class MfaVerifier(Protocol):
    def generate_setup(self, account_label: str) -> EncryptedMfaSetup: ...
    def verify_totp(self, secret_reference: bytes, code: str, now: datetime) -> int: ...
    def issue_recovery_codes(self, count: int) -> tuple[str, ...]: ...
    def hash_recovery_code(self, code: str) -> bytes: ...


class UserRepository(Protocol):
    def find_login(self, identifier: str) -> AccountCredentials | None: ...
    def get_scoped(self, id: UUID, scope: SelfAuthScope) -> Account | None: ...
    def save(self, account: Account, expected_version: int) -> None: ...


class SessionRepository(Protocol):
    def find_active(self, token_hash: bytes, now: datetime) -> Session | None: ...
    def list_owned(self, user_id: UUID, scope: SelfAuthScope) -> tuple[Session, ...]: ...
    def revoke_all(self, user_id: UUID) -> int: ...
    def save(self, session: Session) -> None: ...
    def consume_token(self, token_hash: bytes, purpose: str, now: datetime) -> UUID: ...


class MfaRepository(Protocol):
    def get_factor_for_update(self, account_id: UUID, scope: SelfAuthScope) -> MfaFactor | None: ...
    def get_pending_factor_for_update(
        self, account_id: UUID, setup_token_hash: bytes, browser_hash: bytes, scope: SelfAuthScope
    ) -> MfaFactor | None: ...
    def invalidate_pending_setup(self, account_id: UUID, scope: SelfAuthScope) -> int: ...
    def get_challenge_for_update(
        self, token_hash: bytes, browser_hash: bytes
    ) -> MfaChallenge | None: ...
    def find_recovery_for_update(
        self, factor_id: UUID, code_hash: bytes
    ) -> RecoveryCode | None: ...
    def save_factor(self, factor: MfaFactor, expected_version: int) -> None: ...
    def save_challenge(self, challenge: MfaChallenge) -> None: ...
    def consume_recovery(self, code: RecoveryCode) -> None: ...
    def save_recovery_codes(
        self, factor_id: UUID, codes: tuple[RecoveryCode, ...], scope: SelfAuthScope
    ) -> None: ...
    def revoke_recovery_codes(self, factor_id: UUID, scope: SelfAuthScope) -> int: ...


class RequestDigests(Protocol):
    def request_digest(self, body: Mapping[str, str], version: str | None = None) -> bytes: ...
    def matches_request(self, recorded: bytes, body: Mapping[str, str]) -> bool: ...


class AbuseControls(Protocol):
    """Configured infrastructure limiter; outage raises and denies the operation."""

    def check(self, operation: str, identity: str, network: str) -> None: ...


class IdentityTransaction(Protocol):
    """Existing UnitOfWork plus private credential/idempotency/outbox plumbing.

    Concrete repositories share this transaction. Token issuance stores only
    hashes; notification composition owns protected delivery payloads.
    """

    @property
    def users(self) -> UserRepository: ...
    @property
    def sessions(self) -> SessionRepository: ...
    @property
    def mfa(self) -> MfaRepository: ...

    def __enter__(self) -> IdentityTransaction: ...
    def __exit__(self, *args: object) -> None: ...
    def credential(self, account_id: UUID, scope: SelfAuthScope) -> Credential: ...
    def save_credential(self, credential: Credential) -> None: ...
    def store_token(self, token: IssuedToken) -> None: ...
    def invalidate_tokens(self, account_id: UUID) -> None: ...
    def enrolment_digest(self, account_id: UUID, key: UUID, now: datetime) -> bytes | None: ...
    def record_enrolment(
        self, account_id: UUID, key: UUID, digest: bytes, expires: datetime
    ) -> None: ...
    def notify(self, account: Account, token: IssuedToken) -> None: ...
    def commit(self, action: str, account_id: UUID | None) -> None: ...
